apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kubernetes
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.7.0
  name: pyrra-kubernetes
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubernetes
      app.kubernetes.io/name: pyrra
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubernetes
        app.kubernetes.io/name: pyrra
        app.kubernetes.io/version: 0.7.0
    spec:
      containers:
      - args:
        - kubernetes
        - --disable-webhooks=false
        image: ghcr.io/pyrra-dev/pyrra:v0.7.0
        name: pyrra
        ports:
        - containerPort: 9099
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: certs
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: pyrra-kubernetes
      volumes:
      - name: certs
        secret:
          secretName: pyrra-webhook-validation
