apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.7.5
  name: pyrra-api
  namespace: monitoring
