apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kubernetes
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.7.0-rc.1
  name: pyrra-kubernetes
  namespace: openshift-monitoring
spec:
  ports:
  - name: http
    port: 9444
    targetPort: 9444
  - name: webhooks
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/component: kubernetes
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/part-of: kube-prometheus
