apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    prometheus.io/operator: "true"
  name: prometheus-operator-reconcile-errors
  namespace: test-mika
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: prometheus_operator_reconcile_errors_total{job="prometheus-operator"}
      grouping:
      - controller
      total:
        metric: prometheus_operator_reconcile_operations_total{job="prometheus-operator"}
  target: "95"
  window: 2w
