apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    prometheus.io/operator: "true"
  name: coredns-response-errors
  namespace: test-mika
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: coredns_dns_responses_total{job="kube-dns",rcode="SERVFAIL"}
      total:
        metric: coredns_dns_responses_total{job="kube-dns"}
  target: "99.99"
  window: 2w
