name: generate
on:
  push:
    branches:
      - main
    paths:
      - examples/**
  pull_request:

jobs:
  jsonnet:
    runs-on: ubuntu-latest
    name: Generate Jsonnet examples
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5.0.2
      with:
        go-version-file: go.mod
    - uses: zendesk/setup-jsonnet@v11
    - run: go install github.com/brancz/gojsontoyaml@latest
    - run: make --always-make examples && git diff --exit-code
